// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pizza_mama.Data;

#nullable disable

namespace pizza_mama.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("pizza_mama.Models.Pizza", b =>
                {
                    b.Property<int>("PizzaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ingredients")
                        .HasColumnType("TEXT");

                    b.Property<string>("nom")
                        .HasColumnType("TEXT");

                    b.Property<float>("prix")
                        .HasColumnType("REAL");

                    b.Property<bool>("vegetarienne")
                        .HasColumnType("INTEGER");

                    b.HasKey("PizzaID");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Pizzas");
                });

            modelBuilder.Entity("pizza_mama.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("pizza_mama.Models.Pizza", b =>
                {
                    b.HasOne("pizza_mama.Models.Utilisateur", "Utilisateur")
                        .WithMany("Pizzas")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("pizza_mama.Models.Utilisateur", b =>
                {
                    b.Navigation("Pizzas");
                });
#pragma warning restore 612, 618
        }
    }
}
